# Generated by Django 3.2.4 on 2021-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='book',
            field=models.ManyToManyField(related_name='book', to='books.Book'),
        ),
    ]
