# Generated by Django 3.2.4 on 2021-08-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book',
        ),
    ]
