# Generated by Django 3.2.4 on 2021-08-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_category_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
