# Generated by Django 3.2.4 on 2021-08-19 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='favorited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
